'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8009
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UcPaging

    '''<summary>
    '''_TongSoBanGhi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _TongSoBanGhi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_CurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _CurrentPage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_PageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _PageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_SoBanGhiTrongPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _SoBanGhiTrongPage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_DefaultShowPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _DefaultShowPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_ShowPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _ShowPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''plhShowing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plhShowing As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblBanGhiFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBanGhiFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBanGhiTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBanGhiTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTongSoBanGhi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTongSoBanGhi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _previous As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptCurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCurrentPage As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''_next control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _next As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
End Class
