'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class BTAirTicketRequest

    '''<summary>
    '''panMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hItemID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSEmployeeCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSEmployeeCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSEmployeeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSEmployeeName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSDepartureFrom As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSDepartureFrom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSDepartureTo As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSDepartureTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSearchEmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchEmpInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShowAddOtherAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowAddOtherAirTicket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvPrepared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvPrepared As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvRejected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvRejected As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSubmitted As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvApproved As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''upAirTicketRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAirTicketRequest As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hRequestID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblRequestStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRequesterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequesterCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hRequester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hRequester As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnGetRequesterInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetRequesterInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtRequesterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequesterName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRequesterDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequesterDivision As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRequesterDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequesterDepartment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFromCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFromCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tdRequestDestinationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRequestDestinationLabel As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdRequestDestinationControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRequestDestinationControl As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlFromDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFromDestination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''td1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlToDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToDestination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dteDepartureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDepartureDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dteReturnDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteReturnDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtRequestBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPurpose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurpose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkRequestAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRequestAirTicket As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trRelativeFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRelativeFrom As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlRelativeFromCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelativeFromCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''td3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelativeFromDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelativeFromDestination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trRelativeTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRelativeTo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlRelativeToCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelativeToCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''td5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelativeToDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelativeToDestination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trRelativeTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRelativeTime As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''dteRelativeDepartureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteRelativeDepartureDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dteRelativeReturnDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteRelativeReturnDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtRelativeName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td7 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td8 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td9 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td10 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td11 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td12 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tblAddMore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAddMore As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtRelativeName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td13 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td14 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td15 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td16 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td17 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td18 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td19 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td20 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td21 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td22 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td23 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td24 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRelativeName10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelativeName10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''td25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td25 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td26 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlRelationship10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelationship10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divBtnAddMore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBtnAddMore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hAddMore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAddMore As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnShowSaveOtherAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSaveOtherAirTicket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSaveOtherAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveOtherAirTicket As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShowSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnConfirmRecall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmRecall As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnRecall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRecall As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelOtherAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelOtherAirTicket As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel90 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panSubmitInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSubmitInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSubmitComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmitComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvStatusHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvStatusHistory As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
