'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8670
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class BTInvoicing

    '''<summary>
    '''panMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hItemID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSSerialNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSInvoiceNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSInvoiceNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSInvoiceDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSInvoiceDateFrom As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSInvoiceDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSInvoiceDateFrom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSInvoiceDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSInvoiceDateTo As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSInvoiceDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSInvoiceDateTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trGeneral1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtSSellerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSellerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSSellerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSSellerName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSupplier As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSSupplier As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSEmployeeCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSEmployeeCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlSItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hSItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSItem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSDepartureFrom As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSDepartureFrom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteSDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteSDepartureTo As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hSDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSDepartureTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSearchEmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchEmpInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTInvoice As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hInvoiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hInvoiceID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtInvSTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvSTT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInvNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteInvDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteInvDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtInvSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvSerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInvSellerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvSellerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInvSellerTaxCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvSellerTaxCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''spiInvNetCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiInvNetCost As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblInvNetCostCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvNetCostCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spiInvVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiInvVAT As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblInvVATCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvVATCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spiInvTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiInvTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvTotalCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvTotalCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlInvItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInvItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trInvoiceCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInvoiceCredit As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkInvoiceCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInvoiceCredit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnShowSaveInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSaveInvoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSaveInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveInvoice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelInvoice As Global.System.Web.UI.WebControls.Button
End Class
