'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8794
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class BTOneDayDeclaration

    '''<summary>
    '''panMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel13 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkFINStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFINStatus As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblFINComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFINComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdOraStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdOraStatus As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkOraStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOraStatus As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''grvFIStatusHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvFIStatusHistory As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel12 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCredit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''chkCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCredit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hIsDGMAndAbove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hIsDGMAndAbove As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hIsGMAndAbove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hIsGMAndAbove As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hDeleteUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDeleteUsers As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBusinessTripNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinessTripNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hsBTNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsBTNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlBTType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBTType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hsBTType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsBTType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trGeneral1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hsEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsEmployeeCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFullName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hsFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsFullName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trGeneral2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hLocationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hLocationID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDivision As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hDivisionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDivisionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trGeneral3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hDepartmentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDepartmentID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSection As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSectionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSectionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hGroup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hGroupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trGeneral4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPosition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trGeneral0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral0 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''dteDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDepartureFrom As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hsDepartureFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsDepartureFrom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDepartureTo As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''hsDepartureTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsDepartureTo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlBudgetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBudgetName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hsBudgetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsBudgetName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''spanBudgetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanBudgetAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkBudgetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBudgetAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hsBudgetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hsBudgetAll As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trGeneral6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtProjectBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trGeneral5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGeneral5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtBudgetRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetRemain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchEmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchEmpInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTRegister As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTSubmitted As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTRejected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTRejected As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTCompleted As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel24 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTCancelled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTCancelled As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblDailyAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDailyAllowance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMovingTimeAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMovingTimeAllowance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOther As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalAdvance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestGA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestGA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel14 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTRequest As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel15 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hRequestID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''btnDepartureDateChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDepartureDateChange As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txeFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txeFromTime As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''txeToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txeToTime As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ddlToLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''spanMovingTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanMovingTime As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''chkMovingTimeAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMovingTimeAllowance As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMovingTimeTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMovingTimeTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hActualMovingTimeAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hActualMovingTimeAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hMovingTimeAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hMovingTimeAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''chkCarRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarRequest As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAirTicketRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAirTicketRequest As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTrainTicketRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTrainTicketRequest As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hBreakfastUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hBreakfastUnit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hLunchUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hLunchUnit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hDinnerUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDinnerUnit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hMotobikeFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hMotobikeFee As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''chkBreakfastAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBreakfastAmount As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkLunchAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLunchAmount As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDinnerAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDinnerAmount As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtBreakfastQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakfastQty As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtLunchQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLunchQty As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtDinnerQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDinnerQty As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtBreakfastUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakfastUnit As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtLunchUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLunchUnit As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtDinnerUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDinnerUnit As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtBreakfastAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakfastAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtLunchAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLunchAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtDinnerAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDinnerAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtTaxiQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaxiQty As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtMotobikeQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotobikeQty As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtTaxiFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaxiFee As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtMotobikeFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotobikeFee As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtTotalTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalTransport As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtTaxiDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaxiDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMotobikeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotobikeDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txaPurpose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txaPurpose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteRequestDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''UpdatePanel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel16 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnShowSaveRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSaveRequest As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSaveRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdUploadCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdUploadCaption As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''panRegisterAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRegisterAttachments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdUpload1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''panOthersAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panOthersAttachments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdUpload3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdUploadDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdUploadDesc As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel18 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBTAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBTAirTicket As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel29 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hAirTicketID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAirTicketID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dteAirDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteAirDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtAirline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirline As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAirTicketNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirTicketNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAirRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirRouting As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''spiAirFare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirFare As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''spiAirVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirVAT As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''spiAirAPTTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirAPTTax As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''spiAirSF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirSF As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''spiAirNetPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirNetPayment As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''ddlAirCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAirCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAirExrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAirExrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spiAirExrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spiAirExrate As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''ddlAirPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAirPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlOraSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOraSupplier As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel30 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnShowSaveAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSaveAirTicket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSaveAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAirTicket As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAirTicket As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''spanExportBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanExportBT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnExportBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShowSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSave As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinish As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShowSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowConfirmBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowConfirmBudget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowApprove As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spanApproveLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanApproveLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowBudgetReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowBudgetReject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowReject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowRejectToBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowRejectToBudget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnShowResetAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowResetAdvance As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnResetAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetAdvance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShowCancelBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowCancelBT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCancelBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmRecall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmRecall As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnRecall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRecall As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel11 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtSelectEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectEmployeeCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSelectBTType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSelectBTType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSelectBudgetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSelectBudgetName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkSelectBudgetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSelectBudgetAll As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hSelectBudgetByEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSelectBudgetByEmp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSelectBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hSelectBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSelectBudgetCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSelectProjectBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectProjectBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel20 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panRejectInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRejectInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtRejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRejectReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hOldBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hOldBudget As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnBudgetReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBudgetReject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRejectToBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectToBudget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tabApproveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabApproveMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hApproveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hApproveMessage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''approveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents approveMessage As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''dteInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteInvoiceDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''dteGLDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteGLDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''ddlBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBatchName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''radCash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCash As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''radBankTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBankTransfer As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''btnApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApprove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnApproveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproveCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel90 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panSubmitInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSubmitInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSubmitComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmitComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel17 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panConfirmBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panConfirmBudget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConfirmComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnConfirmBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmBudget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel21 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hCopyUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hCopyUsers As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel22 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hchooseEmpID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hchooseEmpID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''grvChooseEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvChooseEmployee As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btnCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopy As Global.System.Web.UI.WebControls.Button
End Class
