'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8784
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class MasterData

    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''divSystemParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSystemParameter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSystem As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hSystemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSystemID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCodeSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeSys As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValueSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValueSys As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTextSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTextSys As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''speOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speOrder As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel11 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSystem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSystem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDestination As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel37 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvCountryGroup As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel38 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hCountryGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hCountryGroupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCountryGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountryGroupName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCountryGroupDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountryGroupDes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkCountryGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel39 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCountryGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelCountryGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel24 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvCountry As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel44 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hCountryID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountryGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCountryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountryCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCountryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountryName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel45 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCountry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelCountry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel16 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvDesGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvDesGroup As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel17 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hDestinationGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDestinationGroupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtDesGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesGroupName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDesGroupDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesGroupDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkGroupStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGroupStatus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel18 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveDesGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDesGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelDesGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDesGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvDestination As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hDestinationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDestinationID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cboCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDesGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDesGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtaDesName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaDesName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtaDesNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaDesNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDestination As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDestination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDestination As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTitleGroup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel19 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hTitleIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTitleIDs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''grvTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvTitleGroup As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel20 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hTitleGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTitleGroupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtTitleGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitleGroupName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hGroupTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hGroupTitle As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTitle As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

    '''<summary>
    '''chkTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTitleGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTitleGroupNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitleGroupNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel21 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTitleGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTitleGroup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divBTPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBTPolicy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvExpense As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hExpense As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlJobBand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobBand As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtGroupTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroupTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlExpenseBTType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExpenseBTType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExpBreakfast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpBreakfast As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpLunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpLunch As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpDinner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDinner As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpOtherMeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpOtherMeal As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpHotel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpHotel As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpTransport As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpenseMotobike control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpenseMotobike As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpOther As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtExpNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dteExpenseEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteExpenseEffectiveDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''UpdatePanel55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel55 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveExpense As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelExpense As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel40 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvAllowance As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel41 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hAllowanceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAllowanceID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlAllowanceCountryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAllowanceCountryGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAllowanceCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAllowanceCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''speAllowanceAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speAllowanceAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''txtAllowanceDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowanceDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel42 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAllowance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBudget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGetOraBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetOraBudget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grvBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBudget As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hBudget As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBudgetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBudgetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBudgetAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetAmount As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''ddlDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBGType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBGType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBudgetDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetDes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkBudgetIsExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBudgetIsExecutive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkBudgetActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBudgetActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel12 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveBudget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelBudget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel46 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBudgetPIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBudgetPIC As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel47 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hBudgetPIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hBudgetPIC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBudgetPICOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetPICOrg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBudgetPICName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetPICName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBudgetPICEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBudgetPICEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel48 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveBudgetPIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveBudgetPIC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelBudgetPIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelBudgetPIC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divInvoicing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInvoicing As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel13 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvInvoiceItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvInvoiceItem As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel14 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hInvoiceItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hInvoiceItemID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtInvoiceItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceItemName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInvoiceItemNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceItemNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkInvItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInvItem As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel15 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel34 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvCompany As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel35 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hCompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hCompanyID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompanyTaxCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyTaxCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCompanyCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCompanyCheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCompanyDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel36 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCompany As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelCompany As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divAirTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAirTicket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel22 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hOraSupplierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hOraSupplierID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''grvSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSupplier As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel23 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hSelectSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSelectSuppliers As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtSupplierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSupplierType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grvGetDataOraSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvGetDataOraSupplier As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel43 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel25 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvAirPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvAirPeriod As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel26 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hAirPeriodID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAirPeriodID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtAirName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAirDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkAirActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAirActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel27 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveAirPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAirPeriod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAirPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAirPeriod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divOraInvBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOraInvBatchName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel28 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grvBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBatchName As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel29 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hBatchNameID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hBatchNameID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBatchNameDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNameDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkBatchNameActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBatchNameActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel30 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveBatchName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelBatchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelBatchName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divDailyExrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDailyExrate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel31 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGetOraExrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetOraExrate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grvDailyRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvDailyRate As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdatePanel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel32 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hDailyRateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hDailyRateID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlFromCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFromCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlToCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dteConversionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteConversionDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''speConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speConversionRate As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''chkDailyRateActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDailyRateActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel33 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSaveDailyRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDailyRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelDailyRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDailyRate As Global.System.Web.UI.WebControls.Button
End Class
